# Copyright 2020-2021 The Khronos Group, Inc.
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-mobile:
    name: "Build ${{ matrix.sdk }}"
    strategy:
      matrix:
        include:
          - platform: android
            sdk: android
            architectures: arm64-v8a
    env:
      PARALLEL: -j 4

    runs-on: ubuntu-latest  # Use only Ubuntu for Android build
    steps:
      - uses: actions/checkout@main

      - name: update_glslang_sources.py
        shell: bash
        working-directory: ${{github.workspace}}
        run: ./update_glslang_sources.py

      - name: Configure glslang for Android ARM64
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. -DANDROID_PLATFORM=24 -DANDROID_ABI=$ANDROID_ABI -DCMAKE_SYSTEM_NAME=Android -DANDROID_TOOLCHAIN=clang -DANDROID_ARM_MODE=arm -DCMAKE_MAKE_PROGRAM=$ANDROID_NDK_LATEST_HOME/prebuilt/linux-x86_64/bin/make -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake


      - name: Build SPIRV-Cross for Android ARM64
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          cmake --build .. --config Release --parallel 4
          cmake --build .. --config Release --target install
           
          find ./output -name '*' -execdir $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip {} \;

      - uses: actions/upload-artifact@main
        with:
          name: android-arm64-binaries
          path: build/output
